# ====================================================================================================
#   로컬 개발 환경 설정
# ====================================================================================================


spring:
  config:
    activate:
      on-profile: dev

  # 로컬 개발을 위한 사용될 데이터베이스 구성 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  # SQL 초기화 설정
  sql:
    init:
      # SQL 스크립트 초기화 설정 : 내장 데이터베이스일 경우 스크립트 실행
      mode: EMBEDDED
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  h2:
    console:
      enabled: true

  # JSON 데이터 변환 규칙
  jackson:
    deserialization:
      # 정의되지 않은 필드 유입시 예외 발생 허용
      fail-on-unknown-properties: true

  # 웹 브라우저의 새로고침을 통해 화면단의 변경 사항 적용을 위한 뷰 템플릿 경로 및 정적 리소스 경로 지정
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false
  web:
    resources:
      static-locations: file:src/main/resources/static/


logging:
  file:
    path: ${LOG_PATH}
  level:
    root: info
    com.suvin.nepia: debug


server:
  port: 80