# ====================================================================================================
#   운영 환경 설정
# ====================================================================================================


spring:
  config:
    activate:
      on-profile: prod

  # 데이터베이스 구성 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  # JSON 데이터 변환 처리
  jackson:
    deserialization:
      # 정의되지 않은 필드 유입시 예외 발생 허용 비활성화
      fail-on-unknown-properties: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 36000


logging:
  file:
    path: ${LOG_PATH}
  level:
    root: info
    org.suvin.nepia: info


server:
  port: 8989